### PR TITLE
MM App B: Art updates and text changes

### PR DESCRIPTION
**Pull request by orjanbp**
Another PR into Appendix B to

- Update the art on more pages
- Change the "Damned" variant to "Acolyte of the Damned" (just a bit of a personal preference thing) and some text changes on it 
- Move the text on the druid page
- Small update to the ranger beast companion variant text
- Update the back-page to reflect team changes

All that remains beyond that, providing all else looks good for the team, is to add the paper notes in, convert them from green notes to the real deal with Figma.

Going to do that in this pull request before it is merged, just have not done it yet. 👍

GMB link to see the contents of this PR 
https://www.gmbinder.com/share/-MTLHvuaLKirneEgmUfF

Note-points of still to do in this PR: 

- [x] Fix the different small text trouble, using the wrong words here and there
- [x] Try to rework the druid shapeshifting parts, see how that goes
- [ ] Figure out whether to do anything about the mage / necromancer spellcasting situation
- [x] Add the "Speak with Beasts and Plants" feature to the Druids

### CODE REVIEW

**Comment by AceAzzermeen** [comment]
Comments:

-Archdruid
I think the archdruid could use a little buff to it's martial abilities. 
Wouldn't even affect CR because it is supposed to cast spells for 3 turns.

-Druid
I know this would take up more space but i think the statblock should have note for shapeshift.

-Guard
Really like the "offering directions" part.

-Ranger
Maybe have careful aim say "ranged weapon attack" instead of just the longbow.

bugs:
-Archdruid: missing a +1 from prof on it's martial actions.
-Assassin: Calculator CR is 8, statblock says 9.
-Infiltrator: Sneak attack mentions "spy".
-Mage/Necromancer: The cr 4 necromancer has better spellcasting stats than the cr 5 mage?

**Comment by Tyloris** [comment]
The necromancer's spellcasting trait calls it a mage.

**Comment by Tyloris** [comment]
If the druid just has the shapeshifting trait and an extra attack (not a charge ability, for example), then it might be able to fit.

**Comment by Tyloris** [comment]
Alternatively, a variant block underneath the Gladiator that lists a couple forms and which druid organization they belong to (Druids of the Talon, Claw, etc.) might also work.

**Review by MythMaker26 — APPROVED** [review]

**Pull request merged**
