### PR TITLE
Update Chapter 1 Races

### LINKED ISSUE #693: Goblin: DODGE
From the race description:

> DODGE. You may give yourself advantage on a Dexterity saving throw against an effect that you can see, such as a trap or a spell. You can choose to do so before or after the roll, but before any effects of the roll are applied. You can't use this feature again until you finish a short or long rest.

Issue: Advantage always has to be called before rolling, unless I've missed something fundamental!

Solution: can just change it to the wording Luck uses

### PR DESCRIPTION
**Pull request by Tyloris**
Fixes #693 
Fixes some odd wording/lack of italicization on Arcane Knowledge trait (blood elf and forsaken elf).

### CODE REVIEW

**Comment by orjanbp** [comment]
Any other pending Races chapter issues that could be solved here took, since this is a broader PR for the races chapter?

<https://github.com/WC5E/Warcraft-5e-Conversion/labels/%F0%9F%93%84%20race>

**Comment by orjanbp** [comment]
#750 Probably could be included, though the other two may be a bit out of errata scope.

**Comment by Tyloris** [comment]
#754 and #693 are both errata level changes.

**Comment by orjanbp** [comment]
#754 has a bit more profound gameplay impact, beyond just clarifying intent like #693 and #750 would. Run a little discussion on it and then figure out what to do?

**Review by OmNomDom308 — APPROVED** [review]

**Comment by OmNomDom308** [comment]
Id agree the spellcasting modifier should be Cha for those spells: again to fit the theme of them being primarily paladin spells, and bc draenei do get mostly Cha bonues. If they got Wisdom bonuses, Id say Wisdom be fine here.

**Comment by AceAzzermeen** [comment]
The wording could be like with the reworked races from the Guide to the Multiverse Book:

`Intelligence, Wisdom, or Charisma is your spellcasting ability for these spells when you cast them with this trait (choose when you select this race).`

**Comment by orjanbp** [comment]
Ooh that is an interesting idea @AceAzzermeen, present a few different options and just let the player decide which one to go for. 

I propose that this PR closes as just a fix for #693, and then another PR can open with a fix for #754. That would be the tidiest approach. @Tyloris 

And then after that. I can see this is a PR into another branch that does some Human text errata. So I'd suggest either merging this one directly into Master, and hten doing a separate merge on this other `human-errata-patch` branch ... or just do the branch into branch merge as it has been set up, and then follow after this merge by merging that other branch,.

**Pull request merged**
