### PR TITLE
Reorganize languages for better consistency with modern lore

### PR DESCRIPTION
**Pull request by Maia-Everett**
Hello everyone,

I've updated the languages table for better consistency with official modern lore. You're free to use only parts of this edit or not use it at all.

Justifications for the changes:

Standard Languages:
* Orcish has its own runic writing system instead of using the Common one (source: TFT Maiev mission 2).
* There is no evidence that "Eredic" is a word (zero mentions on Wowpedia). "Eredun", however, is well established, and can work as both the language name and the script name, IMHO.
* Modern Pandaren is not the same language as the Mogu language spoken before the Sundering (source: the quest "[It Was Almost Alive](https://wowpedia.fandom.com/wiki/It_Was_Almost_Alive)", Lorewalker Cho has difficulty translating ancient mogu writing, and [Lorewalker Amai](https://wowpedia.fandom.com/wiki/Lorewalker_Amai#History_lesson) mentions that hardly anyone speaks the old tongue of emperors and scholars anymore). It is, however, undoubtably a descendant of it, as the mogu forced their own language on Pandaria, forcing the pandaren to forget whatever language they had before that. The language spoken by pandaren is also called "Pandaren" in-game.
* The plural of "tauren" is "tauren", not "taurens".

Exotic Languages:
* There is no evidence for a Celestial language existing in the Warcraft setting.
* The Giant language was only mentioned in the non-canon RPG, which considered ogres a type of giants (as an artifact of its D&D roots). [The ogre language](https://wowpedia.fandom.com/wiki/Ogre_(language)) has its own form of writing, which we might as well call "Ogre" for lack of an official name.
* Titan and Shath'Yar are of great importance to historians and archaeologists of Azeroth, yet they were missing from the list.
* This is debatable, but the wording "Lesser Races" has unfortunate real-life implications in my eyes. "Monstrous Races", on the other hand, would be consistent in wording with the Monstrous Races document.

Pandaren:
* Renamed the Mogu language to Pandaren, per above, and mentioned that it's a descendant of Mogu.

### CODE REVIEW

**Review by Frogvall — COMMENTED** [review]
I agree with the changes and the motivations. I must however raise the question of where we draw the line for languages to be mentioned in the exotic table. How about Nerglish, Ravenspeech or Hozen, for example?

**Comment by Maia-Everett** [comment]
Valid points. I personally am in favor of fewer languages on the table, and I think there are good reasons not to include the three you listed:

* Nerglish possibly can't even physically be spoken by non-murlocs.
* Ditto for Ravenspeech and non-arakkoa — I imagine its sounds require bird-like physiology to produce.
* Hozen isn't really a language per se and more like a collection of profane words (ook, dook, wikket, etc.) that hozen insert into their Common speech, and the feeling is usually clear from the context.

I'm not sure Low Common and Ogre should be on the table, either. For one, Low Common is only mentioned in the non-canon RPG, which I think should by itself be grounds for auto-exclusion. For two, it's not really a language by itself per se, and more like a mangled form of Common ("You no take candle") mutually intelligible with regular Common, not something a character will have to explicitly learn.

Ogre might be too niche.

It's worth noting that the vanilla 5e languages table doesn't include every conceivable language under the sun, either, only the languages of the most likely allies and enemies. I included Titan and Shath'Yar for three reasons:

* D&D games often involve dealing with ancient mysteries, so it makes sense to include two ancient cultures that left such a lasting impact on Azeroth's past.
* They're somewhat analogous to Giant and Deep Speech, respectively, in vanilla D&D.
* For Shath'Yar, Old God minions are probably going to be a common enough enemy.

**Comment by Frogvall** [comment]
For the record, I just randomly picked three out of these:
https://wowpedia.fandom.com/wiki/Template:Language_links

I think we need to establish where the line goes before we can finalize the table.

**Review by AceAzzermeen — APPROVED** [review]
Don't know if this affects page formatting but i guess that has to be reviewed at some point anyway.

**Comment by orjanbp** [comment]
@AceAzzermeen Agreed, can merge this now and then make further formatting adjustments (and additional revisions if any feel warranted) as things move along 👍 

The languages part isn't out yet in the 3.0 update yet, so merging this in and then further working on it sounds like a good way to move toward that (e.g. the non-background part of Ch 3).

**Pull request merged**
